home/urls.py
#from django.contrib import admin
#from django.urls import path
from django.conf.urls import url,include
from home.views import home_view,sosyal_detail


app_name='homee'
urlpatterns = [
    
	url(r'^$', home_view, name="home"),
	#url(r'^(?P<slug>[\w-]+)/$', home_detail, name="detail"),
	url(r'^(?P<slug>[\w-]+)/$', sosyal_detail, name="sdetail"),
#url içerisinde verilen name.lere url metoduyla html dosyaları içerisinden ulaşabiliriz.
]


##3

spor/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from home.views import home_view
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
	url(r'^', include('home.urls')),
	#url(r'^', include('ligler.urls')),

	#dolar işareti link daha devam edeceği için ilgili uygulamanın urls.i içerisinde yer almıştır.
	
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/base.html
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-117909464-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-117909464-1');
</script>

{% load static %}
<!DOCTYPE html>
<html lang ="tr">
	<head>
		<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({
          google_ad_client: "ca-pub-6571504885082244",
          enable_page_level_ads: true
     });
</script>
<script async custom-element="amp-auto-ads" src="https://cdn.ampproject.org/v0/amp-auto-ads-0.1.js"></script>
		<meta charset="UTF-8" name="viewport" content="width=device-width, inital-scale=1">
		{% block metalar %}
		<meta name="description" content="Beşiktaş, Galatasaray, Fenerbahçe ve Trabzonspor ile ilgili haberler ve yorumlar">
		<meta name="keywords" content="Beşiktaş, Galatasaray,Fenerbahçe, Trabzonspor, Şenol Güneş, Fatih Terim, Aykut Kocaman, Rıza Çalımbay ">
		<meta name="author" content="Rıdvan Dilmen, Ali Ece">
		<meta name="google-site-verification" content="9ZAWEXyS8S7V_HiM0bKwNjdFt1PKI7AZB7HXmKRgOhM" />
		{% endblock %}
		<title> {% block title %} Futbolzade {% endblock %}</title>
		<link rel="shortcut icon" href="{% static 'img/futbolzade.ico'%}" />
		<link rel="alternate" hreflang="tr" href="http://www.futbolzade.com/" />
		<link  href="{% static 'css/fontawesome-all.css' %}" rel="stylesheet">
		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
		<link {% block csss %} rel="stylesheet" href="{% static 'css/style.css' %}" {% endblock %}>
		
		<link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
		<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
		<script src="{% static 'js/jquery.min.js'%}"></script>
		<script src="{% static 'js/bootstrap.min.js'%}"></script>
		
	
	
	
	</head>

<body>
<amp-auto-ads type="adsense" data-ad-client="ca-pub-6571504885082244"></amp-auto-ads>

	



	
{% block body %}	

{% endblock%}

	<footer class=" foter container-fluid text-center">
	<p>TÜM HAKLARI SAKLIDIR. ©2018 FUTBOLZADE</p>
	</footer>
	
	
</body>
</html>

templates/header.html
{% load static %}
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand l" href="{% url 'homee:home' %}" title ="Futbolun Haber Bankası"><i class="far fa-futbol"></i></i>Futbolzade<i class="far fa-futbol"></i></a>
	</div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	
      <ul class="nav navbar-nav navbar-right">
	  
	  <form class="navbar-form navbar-left" role="search" method="GET" action="">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Ara" name="q" value="{{request.GET.q}}">
        </div>
        <button type="submit" class="btn btn-default">Gönder</button>
      </form>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

templates/header1.html
{% load static %}
<div class="navbar navbar-inverse">
	<div class="container">
		<a class="navbar-brand" href="{% url 'homee:home' %}" title ="Futbolun Haber Bankası">
			<i class="far fa-futbol"></i></i>Futbolzade<i class="far fa-futbol"></i>
		</a>
		<form class="navbar-right" role="search" method="GET" action="">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Ara" name="q" value="{{request.GET.q}}">
        </div>
        <button type="submit" class="btn btn-default">Ok</button>
      </form>



	</div>
</div>




 

templates/ilk_row.html
{% load static %}


<!-- ilk row -->
{% include 'maclar.html' %}

	<div class="row">
	<!-- col-md-8 -->
		<div class="col-md-12 col-sm-12">
		
		<!-- Slider main container -->

		<ul class="nav nav-tabs">
			<li class="active"><a data-toggle="tab" href="#genel">FZ</a></li>
			<li><a data-toggle="tab" href="#BJK">BJK</a></li>
			<li><a data-toggle="tab" href="#FB">FB</a></li>
			<li><a data-toggle="tab" href="#GS">GS</a></li>
			<li><a data-toggle="tab" href="#TS">TS</a></li>
			  
		</ul>
		

  <div class="tab-content">
    <div id="genel" class="tab-pane fade in active"><!-- Ana sayfadaki Haberler -->
		<div class="row">
		<div class=" col-xs-12 col-md-7 col-sm-7"> <!--Genel Haberler -->
		{% for sosyal in sosyaller %}
			<div class="media">
				<div class="media-left media-top">
					<img class="media-object" src="{{ sosyal.isim.image.url }}" alt="...">
				</div>
				
				<div class="media-body">
					<!--<h4>{{sosyal.isim}}</h4> -->
					<p class="ert"><b>{{sosyal.isim}}:</b> "{{sosyal.content1 |truncatechars:200}}".</p>	
				</div>
				
				<div class="abc"> <p> {{sosyal.content2 }}<p>
					<p><b><small>{{sosyal.publishing_date|timesince}} önce</b></small></p>
				</div>
				
			</div>

			{% include 'buttons.html' %}
			{% include 'yorum.html' %}	
		{% endfor %}
			
		</div> <!-- Genel Haberler -->
	
		<div class=" col-xs-12 col-md-5 col-sm-5">  <!-- Fikstür vesaire -->
			{% include 'yazılar.html' %}
			
			
		</div><!-- Fikstür vesaire -->
		</div> 
	 {% include 'sayfalama.html' %}
    </div> <!-- Ana sayfadaki Haberlerin sonu -->
	
    <div id="BJK" class="tab-pane fade"> <!-- BJK bölümü -->
		<div class="row">
			<div class="col-md-7 col-sm-7"> 
			{% for sosyal in bjk %}
				<div class="media">
					<div class="media-left media-top">
						<img class="media-object" src="{{ sosyal.isim.image.url }}" alt="...">
					</div>
					<div class="media-body">
						<p class="ert"><b>{{sosyal.isim}}:</b> "{{sosyal.content1 |truncatechars:200}}".</p>	
					
					</div>
					<div class="abc"> <p> {{sosyal.content2 }}<p> <p><b>{{sosyal.publishing_date|timesince}} önce</b></p>  </div>		
				</div>
				{% include 'buttons.html' %}
				{% include 'yorum.html' %}
			{% endfor %}
			</div><!-- Kim Ne Demiş Köşesi sonu -->
			<div class=" col-xs-12 col-md-5 col-sm-5">  <!-- Fikstür vesaire -->
				{% include 'yazı_bjk.html' %}
			</div><!-- Fikstür vesaire -->
		</div>
    </div> <!-- BJK bölümü sonu -->
	
    <div id="FB" class="tab-pane fade">
        <div class="row">
			<div class="col-md-7 col-sm-7"> 
			{% for sosyal in fb %}
				<div class="media">
					<div class="media-left media-top">
						<img class="media-object" src="{{ sosyal.isim.image.url }}" alt="...">
					</div>
					<div class="media-body">
						<p class="ert"><b>{{sosyal.isim}}:</b> "{{sosyal.content1 |truncatechars:200}}".</p>	
					
					</div>
					<div class="abc"> <p> {{sosyal.content2 }}<p> <p><b>{{sosyal.publishing_date|timesince}} önce</b></p>  </div>		
				</div>
				{% include 'buttons.html' %}
				{% include 'yorum.html' %}
			{% endfor %}
			</div><!-- Kim Ne Demiş Köşesi sonu -->
			<div class=" col-xs-12 col-md-5 col-sm-5">  <!-- Fikstür vesaire -->
				{% include 'yazı_fb.html' %}
			</div><!-- Fikstür vesaire -->
		</div>
    </div>
	
    <div id="GS" class="tab-pane fade">
    <div class="row">
			<div class="col-md-7 col-sm-7"> 
			{% for sosyal in ts %}
				<div class="media">
					<div class="media-left media-top">
						<img class="media-object" src="{{ sosyal.isim.image.url }}" alt="...">
					</div>
					<div class="media-body">
						<p class="ert"><b>{{sosyal.isim}}:</b> "{{sosyal.content1 |truncatechars:200}}".</p>	
					
					</div>
					<div class="abc"> <p> {{sosyal.content2 }}<p> <p><b>{{sosyal.publishing_date|timesince}} önce</b></p>  </div>		
				</div>
				{% include 'buttons.html' %}
				{% include 'yorum.html' %}
			{% endfor %}
			</div><!-- Kim Ne Demiş Köşesi sonu -->
			<div class=" col-xs-12 col-md-5 col-sm-5">  <!-- Fikstür vesaire -->
				{% include 'yazı_gs.html' %}
			</div><!-- Fikstür vesaire -->
		</div>
    </div>
	
	<div id="TS" class="tab-pane fade">
    <div class="row">
			<div class="col-md-7 col-sm-7"> 
			{% for sosyal in ts %}
				<div class="media">
					<div class="media-left media-top">
						<img class="media-object" src="{{ sosyal.isim.image.url }}" alt="...">
					</div>
					<div class="media-body">
						<p class="ert"><b>{{sosyal.isim}}:</b> "{{sosyal.content1 |truncatechars:200}}".</p>	
					
					</div>
					<div class="abc"> <p> {{sosyal.content2 }}<p> <p><b>{{sosyal.publishing_date|timesince}} önce</b></p>  </div>		
				</div>
				{% include 'buttons.html' %}
				{% include 'yorum.html' %}
			{% endfor %}
			</div><!-- Kim Ne Demiş Köşesi sonu -->
			<div class=" col-xs-12 col-md-5 col-sm-5">  <!-- Fikstür vesaire -->
				{% include 'yazı_ts.html' %}
			</div><!-- Fikstür vesaire -->
		</div>
    </div>
	
  </div>

		
		
		
			
			
			
			
			
			
			
			
			
			
			
			
			
			 
			
		
		
		<div class="row">
		
			{% include 'ikinci_row.html' %}  <!-- 12 ile 21 arası haberler burda -->
			
		</div>
			
		</div> <!-- col md-8 sonu -->
		
		
		<div class="col-md-6">
		<div class="row">
	
		</div>
		</div>
	
		</div><!-- ilk row sonu -->
		
			
			
			
		
	
	
<script>
$(document).ready(function(){
    $(".media").click(function(){
        $(this).children('.abc').toggle();
		 
    });
	
	
	 $(".yorumlar").click(function(){
        $(this).next().toggle();
    });
	
	$(".kenar").click(function(){
        $(this).children('.truncate').toggle();
		$(this).children('.gizli').toggle();
		 
    });
	
	$(".mac").click(function(){
        $(this).children('.ayrinti').toggle();
		
		 
    });
	
	   $(".maclarım").click(function(){
        $(this).children('tr').toggle();
		$(this).children('.goster').show();
		 
    });
	
    
});

</script>



	